### ISSUE TITLE
总路线 Roadmap

### ISSUE THREAD

**Issue by lychees** [kyubey-network/kyubey-dex#6]
修复已知的 bug。
- [ ] KBY 的 error 订单。
- [ ] CMU 的 error 订单。
- [ ] 幽灵订单（合约中不存在但网站上有显示的订单）。

目前 error 订单和幽灵订单问题需要找个机会自己研究下是如何复现的，再此之前我们下一轮测试应该保留较少但密集的交易对。（要复现这些 bug 并不容易，之前修过一次，不确定是否已经修复了）

仅使用 CCC 进行新一轮测试。
- [ ] 仅保留 KBY 和 CCC 交易对。
- [ ] 每次刷新后不需要重新登录。
